### ISSUE TITLE
Creating a Japanese Translation

### ISSUE THREAD

**Issue by t-cool** [viebel/kids.klipse.tech#4]
@viebel 

Would it be possible to create a Japanese version to help spread the use of Clojure in Japan?

If it's okay, I would appreciate it if you could tell me about the workflow for creating the translation. 

Since there seems to be a folder for the Chinese version, I assume that the multilingualization has already been worked out.

I'd appreciate your help.

**Comment by viebel** [comment]
@t-cool 
All you need to know is to create a folder named jp and put the translated files there.

**Comment by t-cool** [comment]
@viebel 
Thank you for your permission!
I'll create a folder named ja and put the translated files into the folder!

**Comment by t-cool** [comment]
@viebel 
#5 
I will send Japanese translation via Pull Request.

**Comment by viebel** [comment]
Solved by #5
